config/routes.rb
Rails.application.routes.draw do
  resources :clocks
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calendar.rb
# frozen_string_literal: true

class Calendar
  def initialize(date)
    @current_date = date
  end

  def days(&block)
    days_of_the_month.each_with_index(&block)
  end

  def full_date
    "#{current_day_of_the_week} #{current_day_of_the_month}, #{current_month_and_year}"
  end

  def current_month_and_year
    "#{Date::MONTHNAMES[@current_date.month]} #{@current_date.year}"
  end

  def current_day_of_the_week
    @current_date.strftime("%A")
  end

  def current_day_of_the_month
    @current_date.day
  end

  private

  def days_of_the_month
    start_date = @current_date.beginning_of_month
    end_date = start_date.end_of_month
    (start_date..end_date).map { |date| Day.new(date) }
  end
end

app/models/clock.rb
class Clock < ApplicationRecord
  belongs_to :user

  scope :from_user_since, ->(user, time) { where(user:, time: time..) }

  def self.group_time_by_days
    pluck(:time)
      .group_by(&:to_date)
      .transform_keys(&:to_s)
      .transform_keys { |key| Date.parse(key).day.to_i }
  end
end

app/models/day.rb
# frozen_string_literal: true

class Day
  def initialize(date)
    @date = date
  end

  def of_the_week
    @date.strftime("%a")
  end

  def of_the_month
    @date.day
  end

  def to_identifier
    "#{of_the_week.downcase}-#{of_the_month}"
  end

  def worked_hours(times)
    if times.present? && times.length > 1
      hours, minutes = worked_hours_and_minutes times
      "#{format('%02d', hours.to_i)}h#{format('%02d', minutes.to_i)}m"
    else
      "00h00m"
    end
  end

  private

  def worked_hours_and_minutes(times)
    time_diff = (times.last - times.first).to_i

    [ hours_from(time_diff), minutes_from(time_diff) ]
  end

  def hours_from(time)
    time / 3600
  end

  def minutes_from(time)
    (time % 3600) / 60
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_clock, only: %i[show edit update destroy]
  before_action :set_action, only: %i[new create]

  # GET /clocks or /clocks.json
  def index
    set_calendar
    @clock_in_times = Clock.from_user_since(current_user, Time.zone.now.beginning_of_month).group_time_by_days
    @clocks = Clock.all
  end

  # GET /clocks/1 or /clocks/1.json
  def show; end

  # GET /clocks/new
  def new
    @clock = Clock.new
  end

  # GET /clocks/1/edit
  def edit; end

  # POST /clocks or /clocks.json
  def create
    @clock = Clock.new(check_in_params)

    respond_to do |format|
      if @clock.save
        format.html { redirect_to clock_url(@clock), notice: "#{@action} successful" }
        format.json { render :show, status: :created, location: @clock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clocks/1 or /clocks/1.json
  def update
    respond_to do |format|
      if @clock.update(clock_params)
        format.html { redirect_to clock_url(@clock), notice: "Clock was successfully updated." }
        format.json { render :show, status: :ok, location: @clock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @clock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clocks/1 or /clocks/1.json
  def destroy
    @clock.destroy

    respond_to do |format|
      format.html { redirect_to clocks_url, notice: "Clock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_clock
    @clock = Clock.find(params[:id])
  end

  def set_calendar
    @calendar = Calendar.new Time.zone.today
  end

  # Only allow a list of trusted parameters through.
  def clock_params
    params.require(:clock).permit(:time).merge(user: current_user)
  end

  def check_in_params
    params.permit(:user, :time).merge(user: current_user, time: Time.zone.now)
  end

  def set_action
    @action = Clock.where(user_id: current_user.id).count.even? ? "Check In" : "Check Out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clocks_helper.rb
module ClocksHelper
end

app/views/clocks/_check_in.html.erb
<%= form_with url: clocks_path, method: :post do |form| %>
  <div class="inline">
    <%= form.submit @action, class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/clocks/_clock.html.erb
<div id="<%= dom_id clock %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Time:</strong>
    <%= clock.time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= clock.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this clock", clock, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this clock', edit_clock_path(clock), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/clocks/_form.html.erb
<%= form_with(model: clock, class: "contents") do |form| %>
  <% if clock.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(clock.errors.count, "error") %> prohibited this clock from being saved:</h2>

      <ul>
        <% clock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :time %>
    <%= form.datetime_field :time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/clocks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing clock</h1>

  <%= render "form", clock: @clock %>

  <%= link_to "Show this clock", @clock, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to clocks", clocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/clocks/index.html.erb
<div class="w-full">
  <p><%= @calendar.full_date %></p>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-xl">Clocked-in time for <%= @calendar.current_month_and_year %></h1>
  </div>

  <div class="grid grid-cols-7 gap-2">
  <% @calendar.days do |day, i| %>
    <div id="<%= day.to_identifier %>" class="rounded bg-blue-600">
      <p><%= day.of_the_week %> <%= day.of_the_month %></p>
      <p><%= day.worked_hours @clock_in_times[i+1] %></p>
    </div>
  <% end %>
  </div>

  <div id="clocks" class="min-w-full">
    <%= render @clocks %>
    <%= link_to 'New clock', new_clock_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
</div>

app/views/clocks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New clock</h1>

  <%= render "check_in" %>

  <%= link_to 'Back to clocks', clocks_path, class: "m-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/clocks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @clock %>

    <%= link_to 'Edit this clock', edit_clock_path(@clock), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this clock', clock_path(@clock), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to clocks', clocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pontik</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>